spring:
  config:
    activate:
      on-profile: docker

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "canonicalTrade:com.example.instructions.model.CanonicalTrade"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.example.instructions.model.CanonicalTrade"
